### ISSUE TITLE
English Paper - How to auto format "Abbildungen" 

### ISSUE THREAD

**Issue by JCFactory** [informatik-mannheim/term-paper-template#3]
I'm writing my paper in English, mentioning some figures and pictures. But below the images there appears the German word "Abbildung X". Is there a possibility to change the word to "Figure X"? (I tried to change the notation \usepackage[ngerman]{betababel} to \usepackage[english]{babel} in the file "preambel" but LateX throws exceptions...

**Comment by thomsmits** [comment]
Changing ` \usepackage[ngerman]{betababel}` to ` \usepackage[english]{betababel}` or ` \usepackage[english]{babel}` is correct. You have to remove all intermediary LaTeX files to avoid error messages.

The easiest way is to use the `Makefile` and issue a `make clean` from the console or simply remove the `temp` and `result` folder.
