### ISSUE TITLE
Abhängigkeiten für das Template unter Linux / Template Dependencies using Linux

### ISSUE THREAD

**Issue by M-H-2** [informatik-mannheim/term-paper-template#7]
**Deutsch**
Moin, ich verwende hauptsächlich Linux auf meinen Rechnern und ich fände es ganz hilfreich, wenn man die genauen Abhängigkeiten noch etwas spezifischer auflisten könnte. Ich weiß, dass das bei der Hülle und Fülle von Distributionen eigentlich von einer Person gar nicht umfangreich möglich ist und hätte daher den Vorschlag, dem Repository zu diesem Zweck eine *zusätzliche* Markdown-Datei hinzuzufügen, die dann bei Bedarf von Studenten und Dozenten um die ihnen bekannten Abhängigkeiten ergänzt werden könnte. Diese Datei könnte dann z.B. in der Readme verlinkt werden.

Anlass für diese Idee ist, dass ich selbst suchen musste, welche *TeX Live*-Pakete ich konkret brauche. Zuerst hatte ich das Problem gelöst, indem ich einfach alle Verfügbaren installiert habe, aber da das durchaus *mehrere Gigabyte* Speicherplatz in Anspruch nimmt, habe ich mit einer *Arch Linux*-VM geprüft, welche konkreten Pakete denn jetzt überhaupt für das Template nötig sind und dachte mir, es sei vielleicht für die Zukunft ganz sinnvoll, das hier zu teilen.

**English**
Hello there! I use mainly Linux on my computers and think everyone could benefit from a more specific dependency list concerning Linux packages. I know that that is not really feasible for a single person and that is why my proposal would be to add a new markdown file to the repository that can be extended by students as well as tutors who know the requirements for their specific distribution. Afterwards, it could be linked in the Readme to make finding it a piece of cake.

The reason for this idea of mine is that I spent quite some time trying to figure out the *specific* packages I need because I did not want to "waste" *multiple gigabytes* of storage space by simply installing *every* package concerning *TeX Live*. So, I did exactly that in a fresh *Arch Linux* VM and ended up with a informative list of packages that I'd like to share here so everyone can save time and possibly nerves in the future. :)

**Comment by thomsmits** [comment]
Hallo,

Danke für den Vorschlag, den wir gerne umsetzen können. Für den Anfang wäre es natürlich super, wenn Sie eine solche Readme-Datei erstellen könnten und per Pull-Request dem Repo hinzufügen. So haben wir einen Startpunkt und können von dort aus die Abhängigkeiten für die anderen Distributionen/Betriebssysteme ergänzen.

Mit freundlichen Grüßen

  Thomas Smits

**Comment by thomsmits** [comment]
Fixed by merge
